empty_tuple=()
print("Empty Tuple:", empty_tuple)
int_tuple=(1,2,3,4,5)
print("Integer Tuple:", int_tuple)
str_tuple=("Jayesh","Kumar","Sharma")
print("String Tuple:", str_tuple)
mixed_tuple=(1,"Jayesh",3.14,True)
print("Mixed Tuple:", mixed_tuple)
nested_tuple=(1,("Jayesh","Kumar"),{4:5,6:2},(3.14,True))
print("Nested Tuple:", nested_tuple)